### ISSUE TITLE
Backfeeding from Vdrive to Vbus

### ISSUE THREAD

**Issue by zoe1337** [oxplot/fpx#14]
I was surprised there is no back-to-back MOSFET in the power path - I know this is meant to be a power sink, but if enough bulk capacitance is connected to it, someone might plug it into a port while the caps are still charged.

**Comment by oxplot** [comment]
I'd expect the power supply to have its power path protected by a back-to-back MOSFET. Is there any concern of damage to this board?

**Comment by zoe1337** [comment]
With standards-compliant devices it should not be an issue.

**Comment by oxplot** [comment]
I see. I'll keep this issue as an improvement for the next version. Also, the typical application schematics of STUSB4500 features the back-to-back MOSFET as well:

![screenshot1](https://user-images.githubusercontent.com/483682/92124240-de1d4800-ee40-11ea-951d-66dd56145861.png)


Thanks for bringing this up.
