### ISSUE TITLE
STUSB4500 burned when connected to 20V USB-C cable

### ISSUE THREAD

**Issue by bjkayani** [oxplot/fpx#24]
I programmed the unit to give 20V output and connected it to a supply with a USB meter in between. It properly raised the output to 20V. I unplugged the fpx from the meter but since the meter was pulling power, it kept the USB rail at 20V. I then reconnected the fpx and it immediately smoked and the STUSB4500 chip burnt up. The main power draw occurred at Vdd (pin 24). 

I am not sure why this happened since the chip is tolerant of 20V but maybe only when its expecting 20V will it be tolerant to it. Maybe the fact that the USB rail was 20V to begin with was unexpected although it should be able to handle that. 

I had it working perfectly up till this point and it would program and output voltages properly. 

Any ideas of what could have gone wrong? Have you seen anything like this before in your testing?

**Comment by oxplot** [comment]
Oooo — sorry to hear that!

I haven't had this happen to me despite using it in the exact setup you're describing. Are you sure it was the STUSB4500 chip that went bust and not some other component?

I can't think of anything that would case the ST chip to draw too much power so fast.

**Comment by bjkayani** [comment]
I am sure it was since it was visibly damaged burnt my finger a bit. It also took the uController with it. I replaced both and it is working fine now. I am scared to try to replicate it but will do it for science. 

I really like your design and I hope you have plans to bring it back in stock soon. If not, let me know if I can help you with that.

**Comment by bjkayani** [comment]
I recreated what I did before and it burned again. Here is a link to the video of it burning up. Maybe you can try to replicate on your end. 

[Video Demo](https://photos.app.goo.gl/X7uuMrA85CSuvVx7A)

Could this be because of D5 not working properly? I didnt have the exact part so I bodged in a equivalent SOD-323 schottky. Maybe that is not doing its job.

**Comment by oxplot** [comment]
Thanks for that. I really can't tell besides that I have the same USB-C trigger/monitor device. Not sure if that's doing something funky.

I don't actually have any units left and don't have immediate plans to build more ATM.
